version: "2"
services:
   dbserver:
      build: ./db-service
      environment:
        MYSQL_HOME: /var/lib/mysql
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: cclabs
      ports:
       - "3306:3306"
   appserver:
      build: ./status-service
      ports:
       - "2116:2116"
      depends_on:
       - dbserver
      links:
       - dbserver
